# 请求requests库的相关配置
request:
  timeout: 10

# redis的相关配置
redis:
  host: "localhost"
  port: "6379"
  passwd: "000000"

  production_channel: "proxy:production:channel"

# 校验部分的相关配置
valid:
  url: "http://httpbin.org/ip"

# 线程池相关配置
threadpool:
  num: 4

# mysql相关配置
mysql:
  host: "localhost"
  user: "root"
  passwd: "123456"
  database: "proxypool"

# 刷新机制相关配置
refresh:
  num: 20
  max_ip: 30
